### ISSUE TITLE
Router Store has a null state

### ISSUE THREAD

**Issue by optimatex** [LeonardoGentile/mobx-router5#4]
Hi. I have followed all examples, provided in docs, but my router appears with null state. Here is my implementation:

```
import { createRouter } from 'router5';
import browserPlugin from 'router5/plugins/browser';
import loggerPlugin from 'router5/plugins/logger';
import { mobxPlugin, RouterStore } from 'mobx-router5';

const routerStore = new RouterStore();

const routes = [
  { name: 'signup', path: '/signup' },
  { name: 'user', path: '/user/:uid' },
];

export default function configureRouter(useLoggerPlugin = false) {
  const router = createRouter(routes, { defaultRoute: 'home' })
    .usePlugin(mobxPlugin(routerStore)) // Important: pass the store to the plugin!
    .usePlugin(browserPlugin({}));

  if (useLoggerPlugin) {
    router.usePlugin(loggerPlugin);
  }
  console.log('%c 1router', 'color: #ffcb14', router);
  return { router, routerStore };
}

```

as the results, my router store contains null in `route` props

**Comment by LeonardoGentile** [comment]
Hello,
You don't have `home` route in your routes, have you tried to change the defaultRoute?

**Comment by optimatex** [comment]
@LeonardoGentile I have provided concise routes array, in my current code there is the home route. I have tried to tweak this parameter but it doesn't help me

**Comment by LeonardoGentile** [comment]
Ok, but did you start your router? Do you actually navigate from one route to another as described in [router5 docs](http://router5.github.io/docs/navigation.html)? 

In case you couldn't solve it, please provide a code sample so that I might be able to help you

**Comment by LeonardoGentile** [comment]
Also, is there any piece of code observing the `@observable` variables exposed by the store? Try with a console log inside a mobx [autorun]( https://mobx.js.org/refguide/autorun.html)

**Comment by optimatex** [comment]
@LeonardoGentile thanks for the help. I put all my relevant code here https://codesandbox.io/s/jlxopz1lk5

**Comment by LeonardoGentile** [comment]
As I suspected you don't start your router, please do something like this:

```
// Renders the entire app when the router starts
router.start((err, state) => {
    render(<ObserverApp />, document.getElementById("root"));
});
```
The react app should start after the router is started.
Btw if you are using this with react I suggest you to pair this with my other package: [react-mobx-router5](https://github.com/LeonardoGentile/react-mobx-router5)

**Comment by optimatex** [comment]
oh, sorry. I suppose I did miss this in docs, however, I read almost all pages from here http://router5.github.io/docs. Maybe it can be usefull to others to emphasize this part. 
Anyway, thanks for resolving my issue. And for the cool lib. I'll try react-mobx-router5 too

**Comment by LeonardoGentile** [comment]
No problem, cheers!
