### ISSUE TITLE
Remove .idea?

### ISSUE THREAD

**Issue by LeonardoGentile** [LeonardoGentile/mobx-router5#7]
Need feedback from the guys who forked this or works directly with the source code.

Does my .idea IDE cofig gets in the way? Do you find it useful or you delete it asap?

Thanks

**Comment by nrakic90** [comment]
Doesn't bother me, (WebStorm FTW) but I guess all dotted files/folders are meant to be excluded.

**Comment by LeonardoGentile** [comment]
I have re-added, as I work on two different machines and sharing the test run configurations and other IDE settings helps me a lot. 

I realise this is useless for anybody else but unless it causes troubles (why should it?) I will keep it there.
