### ISSUE TITLE
Compatibility with MobX@5.0.0

### ISSUE THREAD

**Issue by micros123** [LeonardoGentile/mobx-router5#8]
When installing MobX 5+, NPM will fire warnings of react-mobx-router5's dependencies because it requires ^4.0.0. Can this be adjusted to (also) be compatible with ^5.0.0 ?

```
npm WARN mobx-router5@4.2.1 requires a peer of mobx@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-mobx-router5@6.1.1 requires a peer of mobx@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

PS: Sorry for cross-posting but both libraries need to be updated.

**Comment by LeonardoGentile** [comment]
See https://github.com/LeonardoGentile/react-mobx-router5/issues/9#issuecomment-401844688
