### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by omerman** [LeonardoGentile/mobx-router5#9]
Im getting `Could not find a declaration file for module 'mobx-router5'` from my idea VSCode..

I can see an index.d.ts at the `node_modules/mobx-router5/src` folder.. and if I manually move it to be present at the root dir `node_modules/mobx-router5`, then the typings would start working.

Help?

**Comment by LeonardoGentile** [comment]
Hello, 
I was not the one taking care of the types definitions, see the PR #6. 
My typescript experience is very limited, but I guess during the building process the index.d.ts should be moved inside the dist folder, @nrakic90 is that right?

**Comment by omerman** [comment]
I added a PR for copying the the index.d to the dist :) #10

**Comment by nrakic90** [comment]
HI,
Moving typings file (index.d.js) doesn't solve the problem entirely in my opinion. When I do that, I'm getting typescript compilation errors. 
I will also work on this a bit to see what can be done.

**Comment by nrakic90** [comment]
I will need to update typings file a bit, just a few lines. @omerman I guess I can do that after your pull request goes through?

**Comment by omerman** [comment]
The pr only touches the build file, copying it to the dist as part of the build process, so I dont think you need to wait.. :)

**Comment by nrakic90** [comment]
Touche. Will get to it.

**Comment by LeonardoGentile** [comment]
Thanks guys 👍 
Travis really got on my nerves today, the builds failed multiple times for unknown reasons, each time it was fixed by purging the cache..

Anyway, I've released the fixes, would you try it and tell me if typing now work as expected?

**Comment by nrakic90** [comment]
Upgraded to 4.2.2. I can confirm that typings work in the sense of using types for TypeScript compilation. Cannot confirm about the VS Code issue tho.

**Comment by omerman** [comment]
Works :sparkles:

**Comment by snaptopixel** [comment]
FYI, there is no typing for `RouterStore.route` I'll put a PR together, thanks!
